services:
  api:
    build: ./api
    ports: 
      - "4000:4000"
    networks:
      - app-network
    environment:
      - DB_HOST=${DB_HOST}:3306
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/healthcheck"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s

    #restart: on-failure

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app-network
    volumes:
      - ./web/static:/static

networks:
  app-network:
    driver: bridge